remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
